apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-demo-cert
spec:
  secretName: jenkins-demo-cert
  dnsNames:
    - {{ .Values.domainJenkinsDemo }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io
