apiVersion: v2
name: helm-jenkins-operator
version: 1.0.0
appVersion: 1.25.0
description: A Helm chart wrapper for Jenkins Operator

dependencies:
  - name: jenkins-operator
    version: "0.8.0-beta.2"
    repository: "https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart"
    condition: jenkins-operator.enabled
