apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-jenkins-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: demo-jenkins-secret   # name of the k8s Secret to be created
  data:
  - secretKey: user
    remoteRef:
      key: initial-secret
      property: GRAFANA_USER # Intend to use the same user as Grafana

  - secretKey: password
    remoteRef:
      key: initial-secret
      property: GRAFANA_PASSWORD # Intend to use the same password as Grafana
